# Generated by Django 2.2.4 on 2019-09-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DesignerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prof_pic', models.ImageField(upload_to='')),
                ('personaldescription', models.TextField(max_length=500)),
                ('education', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('schooldescription', models.TextField(max_length=50)),
                ('schoolstiestamp', models.DateTimeField(auto_now_add=True)),
                ('skills', models.CharField(max_length=50)),
                ('skillscapacity', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('workingtime', models.DateTimeField(auto_now_add=True)),
                ('jobsdescription', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('senderemail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('time_choosen', models.TimeField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('size', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('datemade', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ArtCategory')),
            ],
        ),
    ]
