# Generated by Django 2.2.4 on 2019-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('dimension', models.IntegerField()),
                ('size', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
