# Generated by Django 2.2.5 on 2019-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(upload_to='user_directory_path'),
        ),
    ]
