# Generated by Django 2.2.5 on 2019-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_art_datemade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Your_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
