# Generated by Django 2.2.4 on 2019-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
