# Generated by Django 2.2.4 on 2019-09-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_art_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='art',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='designerdetails',
            name='description',
        ),
        migrations.AddField(
            model_name='art',
            name='datemade',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='company',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='education',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='job',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='jobsdescription',
            field=models.TextField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='personaldescription',
            field=models.TextField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='school',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='schooldescription',
            field=models.TextField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='schoolstiestamp',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='skills',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='skillscapacity',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='workingtime',
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='art',
            name='caategorie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.ArtCategory'),
            preserve_default=False,
        ),
    ]
