# Generated by Django 2.2.5 on 2019-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_hires'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cv',
        ),
        migrations.AddField(
            model_name='art',
            name='categorie',
            field=models.ManyToManyField(to='portfolio.ArtCategory'),
        ),
    ]
