# Generated by Django 2.2.5 on 2019-10-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cvcategory_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='categorie',
        ),
    ]
